apiVersion: v1
kind: Secret
metadata:
  name: {{ include "projects.fullname" . }}-env
  namespace: projects
  labels:
    {{- include "projects.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  S3_BUCKET: {{ .Values.secrets.s3Bucket | quote }}
  S3_ACCESS_KEY_ID: {{ .Values.secrets.s3AccessKeyId | quote }}
  S3_SECRET_ACCESS_KEY: {{ .Values.secrets.s3SecretAccessKey | quote }}
  {{- if .Values.secrets.s3Endpoint }}
  S3_ENDPOINT: {{ .Values.secrets.s3Endpoint | quote }}
  {{- end }}
  {{- if .Values.secrets.s3Region }}
  S3_REGION: {{ .Values.secrets.s3Region | quote }}
  {{- end }}
  {{- if .Values.secrets.s3PublicUrlBase }}
  S3_PUBLIC_URL_BASE: {{ .Values.secrets.s3PublicUrlBase | quote }}
  {{- end }}
