{{- if .Values.vmServiceScrape.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ include "projects.fullname" . }}
  namespace: {{ .Values.namespace | default "projects" }}
  labels:
    {{- include "projects.labels" . | nindent 4 }}
    role: metrics
spec:
  selector:
    matchLabels:
      {{- include "projects.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: {{ .Values.vmServiceScrape.port }}
    path: {{ .Values.vmServiceScrape.path }}
    interval: {{ .Values.vmServiceScrape.interval }}
{{- end }}
